# Site settings
title: "Title"
author: "Kristin Ashby"
description: "Really cool blog about ... something"
lang: "en"

# Build settings
markdown: kramdown
plugins: _plugins
paginate: 2
exclude: ["gulp"]

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 8                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: false         # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

navigation:                  # (optional) site navigation in the header
  - index.html
  - README.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
  github: "https://github.com/niklasbuschmann/contrast"
  rss: "/contrast/feed.xml"
