# Site settings
title: K.M.Ashby
motto: Your motto
description: > # this means to ignore newlines until "baseurl:"
  Data portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kmashby.github.io/" # the base hostname & protocol for your site
github_username:  kmashby

# Build settings
markdown: kramdown
